services:
  fps:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: ksm
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/drm
    restart: unless-stopped
#    depends_on:
#      - ksm_db
#      - ksm_redis
    command: air main.go -b 0.0.0.0

#  ksm_db:
#    image: postgres:alpine
#    container_name: ksm_db
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#    ports:
#      - ${DB_PORT}:${DB_PORT}
#    volumes:
#      - ./data-dump/postgres:/var/lib/postgresql/data
#
#  ksm_redis:
#    image: redis:alpine
#    container_name: ksm_redis
#    restart: always
#    volumes:
#      - ./data-dump/redis:/data
#    ports:
#      - '6379:6379'
